apiVersion : apps/v1
kind: Deployment
metadata:
  name: "jrkubcls01-bac9"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "jrkubcls01-bac9"
  template:
    metadata:
      labels:
        app: "jrkubcls01-bac9"
    spec:
      containers:
        - name: "jrkubcls01-bac9"
          image: "jasonsrealm.azurecr.io/jrkubcls01"
          ports:
          - containerPort: 9981