apiVersion: v1
kind: Service
metadata:
    name: "jrkubcls01-bac9"
    labels:
        app: "jrkubcls01-bac9"
spec:
    type: LoadBalancer
    ports:
    - port: 9981
      targetPort: 9981
      protocol: TCP
      name: http
    selector:
        app: "jrkubcls01-bac9"